// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svkhheqomflkxqznhmtz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2a2hoZXFvbWZsa3hxem5obXR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MjcyNjgsImV4cCI6MjA3MDUwMzI2OH0.nicIC42GNvvPO9JpvubaXUSrbdgGf3TuJUhdJxmq5is";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});